apiVersion: v1
kind: Service
metadata:
  name: kubekiosk
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: kubekiosk
  type: LoadBalancer
